version: "3.7"

services:
  todo:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: service-todo
    depends_on:
      - postgres
      - nats
    ports:
      - "8080"
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass123"
      NATS_ADDRESS: nats:4222

  query:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: service-query
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass123"
      NATS_ADDRESS: nats:4222
      ELASTICSEARCH_ADDRESS: elasticsearch:9200

  pusher:
    build:
      context: .
      dockerfile: .docker/go/Dockerfile
    command: service-pusher
    depends_on:
      - nats
    ports:
      - 8080
    environment:
      NATS_ADDRESS: nats:4222

  postgres:
    build: .docker/postgres
    restart: always
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: "pass123"

  nats:
    image: nats-streaming:0.20.0
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

  nginx:
    build: .docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - todo
      - query
      - pusher
